apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-external-name-deployment
  labels:
    app: nginx-external-name
spec:
  selector:
    matchLabels:
      app: nginx-external-name
  replicas: 1
  template:
    metadata:
      name: nginx-external-name-pod
      labels:
        app: nginx-external-name
    spec:
      containers:
        - name: nginx-external-name
          imagePullPolicy: IfNotPresent
          image: nginx
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-external-name-service
  labels:
    app: nginx-external-name
spec:
  selector:
    app: nginx-external-name
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  topologyKeys: #就近访问
    - "kubernetes.io/hostname"
    - "*"

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-external-name-service
  labels:
    app: nginx-external-name
spec:
  selector:
    app: nginx-external-name
  type: ExternalName
  externalName: nginx-external-name.com
  