apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-config-deploy
  labels:
    app: test-config
    dept: user-it-dept
  annotations:
    user-it: user1test-test-finalizer
  finalizers: # 资源锁，加上deleteTimestamp
    - kubernetes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-config-pod
  template:
    metadata:
      name: test-config-pod
      labels:
        app: test-config-pod
    spec:
      containers:
        - name: test-config-pod
          image: nginx
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: test-config-pod-volume
              mountPath: /app/k8s-configmap
              readOnly: false
      restartPolicy: Always
      volumes:
        - name: test-config-pod-volume
          configMap:
            name: test-config